# Generated by Django 5.0.6 on 2024-05-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Birds",
            fields=[
                (
                    "name",
                    models.CharField(
                        max_length=128, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("flying_speed", models.IntegerField(default=30)),
                ("emoji", models.CharField(default="🪿", max_length=16)),
            ],
        ),
    ]
